config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'entries#index'
  get 'entries/', to: 'entries#index'
  get 'entries/new', to: 'entries#new', as: "new_entry"
  get 'entries/:id', to: 'entries#show', as: "entry"
  post 'entries/', to: 'entries#create'
  get 'entries/edit/:id', to: 'entries#edit', as: "edit_entry"
  patch 'entries/:id', to: 'entries#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @entries = Entry.all
    @websites = [
      ["http://railsgirls.com", "Rails Girls"],
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
    ]
    render = 'entries/index'
  end

  def show
    @entry = Entry.find(params["id"])
    render 'entries/show'
  end

  def new
    render 'entries/new'
  end

  def create
    # entry_params = params["entry"]
    # entry = Entry.create(entry_params)
    # redirect_to(entry_path(entry))
    #render(:plain => params['entry']['title'].inspect)
    entry = Entry.create(title: params["entry"]["title"], date:Date.current, contents:params["entry"]["contents"])
    redirect_to(entry_path(entry))
  end

  def edit
     @entry = Entry.find(params["id"])
     render 'entries/edit'
  end

  def update
    entry_params = params["entry"].permit("title", "contents")
    entry = Entry.find(params["id"])
    entry.update(entry_params)
    redirect_to(entry_path(entry))
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
  <p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
  <p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
<h1>My Diary</h1>
<%= image_tag("logos/puzzles.jpg") %>
  <div>
    <% for entry in @entries %>
      <h2><%= link_to(entry.title, entry_path(entry)) %></h2>
      <p><%= entry.date %></p>
      <p><%= entry.contents %></p>
    <% end %>
  </div>

  <div>
<h1>My favourite websites</h1>
  <ul>
    <% for url, name in @websites %>
      <li><a href="<%= url %>"><%= name %></a></li>
    <% end %>
  </ul>
</div>

    <%= link_to("New entry", new_entry_path) %>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
 <p><%= form.label("title") %></p>
 <p><%= form.text_field("title") %></p>
 <p><%= form.label("contents") %></p>
 <p><%= form.text_area("contents") %></p>
 <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
  <p><%= link_to("Back to main menu", entries_path) %></p>
  <p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>  
    <title>Diary</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://rawgithub.com/krzysztofbialek/Rails-Girls-Warsaw-App/master/style.css" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>